### PR TITLE
Major update for the GUIs

### PR DESCRIPTION
**Pull request by EternalModz**
Updating everything for the new / upcoming update for the official PCK Studio.

### CODE REVIEW

**Comment by NessieHax** [comment]
could you remove the themes folder and instead use a git submodule to use [your custom theme](https://github.com/EternalModz/CrEaTiiOn-Brotherhood-Official-C-Theme)?

**Comment by MattN-L** [comment]
It fails the checks but is working perfectly in Visual Studio? Not sure what I'm doing wrong here lol

**Comment by NessieHax** [comment]
i'll fix that

**Comment by NessieHax** [comment]
I messed up and put the changes in this: #15

**Pull request closed without merging**
